// Code generated by kessoku. DO NOT EDIT.

package di

import (
	"github.com/mazrean/kessoku"
	"github.com/mazrean/mazrean/todo-by-todo-backend/internal/router"
)

func InjectCLI(addr router.Addr, version router.Version) *router.Router {
	todo := kessoku.Provide(router.NewTodo).Fn()(version)
	router := kessoku.Provide(router.NewRouter).Fn()(addr, todo)
	return router
}
