services:
  app:
    build:
      context: ./go
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
    environment:
      ADDR: :8080
    develop:
      watch:
        - action: rebuild
          path: .
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/example"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      tidb:
        condition: service_started
      database_init:
        condition: service_completed_successfully
  tidb:
    build:
      context: .
      dockerfile: ./tidb.Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3000
      - 2379:2379
    command: ["--tiflash", "0", "--kv.config", "/tikv/config.toml"]
    volumes:
      - ./tidb/tikv.toml:/tikv/config.toml:ro
      - ../tidb/tikv/data:/tikv/data
  database_init:
    image: mysql:8.4.2
    restart: on-failure
    command: mysql -htidb -uroot -P4000 -e "CREATE DATABASE IF NOT EXISTS todo_by_todo;"
    depends_on:
      - tidb
