// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (sql.Result, error)
	CreateUser(ctx context.Context, name string) (sql.Result, error)
	DeleteTodo(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetTodo(ctx context.Context, id int64) (Todo, error)
	GetUser(ctx context.Context, id int64) (User, error)
	ListTodos(ctx context.Context) ([]Todo, error)
	ListTodosByUser(ctx context.Context, userID int64) ([]Todo, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkTodoCompleted(ctx context.Context, id int64) error
	MarkTodoIncomplete(ctx context.Context, id int64) error
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
