// Code generated by kessoku. DO NOT EDIT.

package di

import (
	"github.com/mazrean/kessoku"
	repo "github.com/mazrean/todo-by-todo-backend/modules/todo/internal/repository"
	"github.com/mazrean/todo-by-todo-backend/modules/todo/internal/repository/config"
	"github.com/mazrean/todo-by-todo-backend/modules/todo/internal/router"
)

func InjectCLI(jsonconfig *repo.JSONConfig, environment config.Environment) (*router.Router, error) {
	repository, err := kessoku.Provide(repo.NewJSON).Fn()(jsonconfig, environment)
	if err != nil {
		var zero *router.Router
		return zero, err
	}
	todoRepository := kessoku.Provide(repo.NewTodoRepository).Fn()(repository)
	userRepository := kessoku.Provide(repo.NewUserRepository).Fn()(repository)
	todo := kessoku.Provide(router.NewTodo).Fn()(todoRepository)
	user := kessoku.Provide(router.NewUser).Fn()(userRepository)
	router := kessoku.Provide(router.NewRouter).Fn()(todo, user)
	return router, nil
}
