services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      ADDR: :8080
    develop:
      watch:
        - action: rebuild
          path: .
    healthcheck:
      test: ["CMD", "/bin/grpc-health-probe", "-addr=:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
