name: Deploy

on:
  push:
    branches:
      - main
      - feat/infra
  workflow_dispatch:

env:
  NODE_VERSION: 22

jobs:
  server_build_and_deploy:
    name: Build Server Image
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Set IMAGE_TAG env
        run: echo "IMAGE_TAG=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV
      - uses: actions/checkout@v4.2.2
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.GOOGLE_IAM_WORKLOAD_IDENTITY_POOL_PROVIDER }}
          service_account: ${{ vars.GOOGLE_IAM_SERVICE_ACCOUNT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Auth
        uses: "docker/login-action@v3"
        with:
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          registry: ${{ vars.REGISTRY }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./go/
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ vars.SERVER_IMAGE }}:latest
      - id: "deploy"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          region: ${{ vars.REGION }}
          service: ${{ vars.SERVER_CLOUDRUN_SERVICE }}
          image: ${{ vars.SERVER_IMAGE }}
